name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install Dependencies
      run: npm ci
    - name: Test the markdown
      run: npm run test
    - name: Build the dist
      run: npm run build
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        path: dist
        if-no-files-found: error
    - name: SFTP Deploy
      if: github.ref == 'refs/heads/main'
      uses: wlixcc/SFTP-Deploy-Action@v1.2.1
      with:
        username: ${{ secrets.SSH_USERNAME }}
        server: ${{ secrets.SSH_SERVER }}
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        local_path: './dist/*'
        remote_path: '/var/sites/blacksun.cx/cv/'

